### ISSUE TITLE
Create a new module for HumHub

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#1]
There should be a new module to extend functionalities of [HumHub](https://github.com/humhub). We need to enrich the platform with features for the core as well as for other modules that are used.

At the beginning the highest priority is to extend existing APIs with updating endpoints and adding new endpoints. There are several [issues labeled with "api"](https://github.com/ikuseiGmbH/smart-village-app-humhub-ext/labels/api) regarding these topics, that can be addressed after the new module exists.

Please use this repository to init a new module.
The new module should be installable for HumHub instances like other modules. Its name should be "Smart Village App" with a short description "Provides extended features for integration in the Smart Village App".

---

Please ask questions and add further information that are necessary to create that module.

**Comment by handysolver** [comment]
Hi there,

We have created the module which is a fork of the original rest API hum hub library as we are building the new end points on it.
Its title, description have been setup.
We would like to push the code to this repository.

Can you please grant access to the following github accounts for making a push to this repository:
- handysolver
- gaurav-handysolver

Also, let us know the flow you would prefer. Can we directly push to the main branch.. or do we create pull requests?

Thanks!

**Comment by donni106** [comment]
I have invited you both. Please make pull requests, so that we are able to understand and discuss decisions more precisely.

**Comment by gaurav-handysolver** [comment]
Hi there,
We made a pull request please go over and check once.

**Comment by donni106** [comment]
In general for pull requests, please take care of the following important steps:

<img width="1248" alt="Bildschirmfoto 2022-04-21 um 11 37 22" src="https://user-images.githubusercontent.com/1942953/164445146-0ac6698d-4d95-4a9d-8828-c412bf8b196d.png">

1. reference the related issue
2. add me as reviewer so that i get notified
3. the creator should be the assignee, e.g. to be able to filter at a later point with multiple pull requests
4. add an appropriate label if possible

also please create pull requests for each issue, that we can check one after the other. having one pull request for different topics at the same time makes it more difficult to maintain an overview and move forward effectively.
thanks.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We made a push in issue-1 branch as per your feedback like keywords, minVersion etc. so, please check it once
Thanks!

**Comment by donni106** [comment]
> Hi @donni106 We made a push in issue-1 branch as per your feedback like keywords, minVersion etc. so, please check it once Thanks!

please refer to updates in the specific pull request in the future, where you made the change. there are already open discussions, where you could have mentioned, that work is done. instead of messaging here, you know what i mean?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Okay, next time we'll take care of that
