### ISSUE TITLE
Class 'humhub\modules\smartVillage\humhub\components\Module' not found

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#13]
I have tried to install the module on our staging system.
First, i put it in `humhub/protected/modules` which did nothing.
After that i saw another existing `modules` folder in `humhub/protected/humhub` and moved the module there next to an `installer` folder resulting in: `humhub/protected/humhub/modules/smart-village-app-humhub-ext`.
With this change there is the first reaction online when visiting the website for `/admin/module/list` having the following error: 

![Bildschirmfoto 2022-04-29 um 17 10 34](https://user-images.githubusercontent.com/1942953/165972694-fffd5f38-a591-4186-b931-0296253053f1.png)

Any ideas?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We missed out to put backslash(\) for loading the base module. now it is fixed you can check it.
Thanks!

**Comment by donni106** [comment]
thanks, this fixed it!

|1|2|3|
|---|---|---|
|![Bildschirmfoto 2022-05-02 um 11 37 28](https://user-images.githubusercontent.com/1942953/166214864-b10792fb-51a5-4223-b41b-6c55eb50ff6c.png)|![Bildschirmfoto 2022-05-02 um 11 38 01](https://user-images.githubusercontent.com/1942953/166214873-e91fee61-2486-4db7-9b16-f239836dc125.png)|![Bildschirmfoto 2022-05-02 um 11 38 10](https://user-images.githubusercontent.com/1942953/166214884-d349b66b-00be-4714-a760-6bcc33d14684.png)|
