### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#20]
We should think of a workflow for versioning the module. It is still 0.1 but a few PRs werde merged with additional features.
Do you think each PR should increase the version? Or should we think of combining features for version increases?
What recurring times could be ideal to increase the version?

**Comment by handysolver** [comment]
Hi @donni106 ,

Both could be workable. 
- **New version for every issue PR**
If we are looking at updating the version for every pull request, then we can update it in the module.json and push along with the PR. Example 0.1 to 0.2 and so on.

- **A batch of issues with their PRs lead to a version update**
Maybe you can add an appropriate label on each issue as to which version it should belong to. 
In the last issue's PR we can update the version in module.json

Let us know what can be appropriate.

Thanks

**Comment by donni106** [comment]
Thanks, let's do the second approach.
I added 0.1, 0.2 and 0.3 to closed and open issues and PRs.
the endpoints without authentication will be 0.3.
so before, please create a PR where you update the current version to 0.2, that we can merge to increase the version from 0.1 to 0.2 before we merge something for 0.3. 
if i saw such a PR for version increase once, i think i can manage to do them on my own in the future after relevant PRs being merged.

**Comment by handysolver** [comment]
Hi @donni106 ,

Okay thanks for clarifying further.

Next we will create a PR with branch name "version_0.2" which we will checkout from "main" where we update the version from 0.1 to 0.2 in the following file:

https://github.com/ikuseiGmbH/smart-village-app-humhub-ext/blob/main/module.json

Further, should we need to mention the features implemented till this version in the description or somewhere?

Also code till issue 5 seems to be already merged to main. So I assume all till issue 5 will become part of version 0.2.

Next we are making fixes to issue 6 and will make a push.. Should we change it to 0.3 before making this push for Issue 6 PR. Or will you be managing the versioning yourself beyond 0.2 as mentioned?

Thanks

**Comment by donni106** [comment]
I will take care of the versioning always after things get merged.
You do not need to mention anything.
I will start a changelog file as well to keep track of versioning.
