### ISSUE TITLE
Marking a conversation `'read'` must not update its `updated_at`

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#21]
The implementation for marking conversations `'read'` per #18 was successfully tested. Thanks!
But the `updated_at` must not be updated accordingly. With the current state, a message from 14:03 would get a message from 15:53 if a recipient reads the message at 15:53. When setting `seen_at` to 15:53, `updated_at` needs to stay at 14:03 in `/v2/mail`.

A further problem ist, that if a recipient reads the message, `updated_at` gets updated, the other participant sees the message as `'unread'` again (with new time). The result is, that a conversation is never `'read'` for everyone.

**Comment by donni106** [comment]
A further problem ist, that if a recipient reads the message, `updated_at` gets updated, the other participant sees the message as `'unread'` again (with new time).

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Okay, we will investigated this. But for debugging will we create new branch like issue-21 or done in the original branch (like issue-5).
Thanks!

**Comment by donni106** [comment]
> new branch (issue-21) or done in the original branch(issue-5)

we do not need to reactivate old branches, you can create a new one without hesitation
