### ISSUE TITLE
Add endpoint for membership requests

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#3]
Currently there is no way to request a membership for a space through the API. The functionality is given for the web already and spaces can have the policy for joining only through requests. We need a new POST endpoint `/space/{id}/membership/{userid}/request` which triggers the logics that are already used in the web.

**Comment by gaurav-handysolver** [comment]
Hi There,
Reqeust for space membership through api is developed. so to access the api, you need to user id and space id.
![image](https://user-images.githubusercontent.com/103625795/163986910-13cbba58-a5b5-4a22-9382-66c25a8838c1.png)

**Comment by donni106** [comment]
@gaurav-handysolver it is not meant to add members but that users can request a membership before adding them by accepting requests.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
There is a message field in table which is optional and when we request for space membership through front-end, we fill some data in that message box.
![image](https://user-images.githubusercontent.com/103625795/166245937-4a758483-1f8c-43d5-bb17-4cce9eaa9175.png)
So, do we pass some message while hitting the api?

**Comment by donni106** [comment]
Good question. Is it possible to skip such message? We would not need it. A request through the API should be possible without an introduction text.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Yes we can skip that message because it is an optional field so, we does not need to pass any message while using the API.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
When we request for space memership through web. A notification goes to admin of that space, same this functionality we replicate in our api as well. so, do you need this notification feature in api or not?

**Comment by donni106** [comment]
> Yes we can skip that message because it is an optional field so, we does not need to pass any message while using the API.

ok, so we ignore such message per API.

> so, do you need this notification feature in api or not?

yes please. the admin of the space needs a notification in the same way per API membership requests.
