### ISSUE TITLE
Hide members list in web?

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#33]
Under https://staging.humhub.herzbergdigitalvereint.de/directory/members everyone can see who is registered. The profiles itself are behind a login, that's fine. Is it possible to hide the members list entirely in the web and make the url not accessible publicly?

**Comment by donni106** [comment]
I found out, that the access to the whole directory can be deactivated based on user groups. So I achieved for testing purposes, that https://staging.humhub.herzbergdigitalvereint.de/directory/directory cannot be accessed entirely by certain users. BUT guests can still access the path. I do not found any way to make a setting for this for guests.

**Comment by donni106** [comment]
> Can you tell us how you activated the directory module in humhub?

I have not activated anything for the directory. This seems to be a default. In the roles for user groups permissions can be set for the access as is described:

![Bildschirmfoto 2022-06-29 um 11 38 23](https://user-images.githubusercontent.com/1942953/176404950-afa6647d-b122-488d-91a5-42a7decf77f9.png)

> So, for this we have to set "guestAccess" property as false in protected/config/common.php file like this

currently there is no such file, so i can create that with just those new content?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
This access directory option is not present in our humhub project because of our humhub version (1.10.0) but code files are present in project.

So, you can add this code in humhub/protected/config/common.php file and check this code will restricted guest user or not?

return [
    'modules' => [
        'directory' => [
            'guestAccess' => false 
        ]
    ]
]

![image](https://user-images.githubusercontent.com/103625795/176438118-28d2eec8-c35d-40e4-9b28-8a36e984755f.png)

**Comment by donni106** [comment]
We have no `humhub/protected/config/common.php` file. I will try it in a `humhub/protected/config/common-factory.php`:

<img width="176" alt="Bildschirmfoto 2022-06-29 um 18 55 11" src="https://user-images.githubusercontent.com/1942953/176493267-a9a77c06-0809-46ad-bf36-c2b2ae5f945e.png">

**Comment by donni106** [comment]
That try had no effect.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
You can write that code in web.php as well and test it because in web there is a order which is specified by humhub for configuration code.

![image](https://user-images.githubusercontent.com/103625795/176626203-c4a9988f-79c4-49c5-ac5c-35e3093f6b18.png)

https://docs.humhub.org/docs/admin/advanced-configuration/

**Comment by donni106** [comment]
nothing changed after moving that part to the return array in web.php.
what is your expectation, what should happen with setting that config?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We can override the value of property like guestAccess in web.php so, we  are set guestAccess (false) then it should not be open for guest or guest not access the path (directory access path for guest).

**Comment by donni106** [comment]
Did this work in your tests? Maybe this way does not work with older versions of HumHub like 1.8.3?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Actually, this directory module is not seen in web. code files of directory module is present but it is not visibile in website or there is no setting to enable directory module.

**Comment by donni106** [comment]
With 1.9.3 there is no /directory anymore as it is changed to /people and /spaces with a big overhaul see release notes https://docs.humhub.org/docs/about/releasenotes/release_notes_1_9/

So we can close this issue.
