### ISSUE TITLE
Hide functionalities in web?

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#35]
Is it possible to hide some functionalities in web forms?
For example in the screenshot on the left (1) there are options to add users without invitation or invite all users when creating a space.
Or on the right (2) there are options to show "Decline" or "Maybe" for event decisions.
We do not want to provide any of those.

![Bildschirmfoto 2022-06-23 um 17 13 52-side](https://user-images.githubusercontent.com/1942953/175336331-1ea8a93f-8712-4ad4-b0b4-b6fe6936086b.png)

**Comment by gaurav-handysolver** [comment]
Hello @donni106 
In screenshot(1), yes we can hide the these checkbox in web form.

**Procedure**
1. Go to: Administration->user->groups
2.  click on "setting" icon of that group, you want to hide these functionalities.
3.  select persmission options and open it.
4.  choose "Manage User" persmission and set as "deny".
![image](https://user-images.githubusercontent.com/103625795/176622262-f3cc0834-93c0-4056-bfd6-580f5e2ddd51.png)

Note: We can edit "ADMINISTRATIVE GROUP" or module who has id = "admin" like this 
 
 
![image](https://user-images.githubusercontent.com/103625795/176625534-6c213b31-3b24-4528-9fe8-4fd45165daf0.png)

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We investigated screenshot(2) and we found that there is no option/setting to hide these checkbox because they are attribute and their values are stored in database.

There is one solution which can be possible is to create own new theme like "SmartVillageAppTheme" and in this theme we can remove these checkboxes.

But there can be a side effect when we create our new themem

- on Humhub or module upgrade, the theme might have to be manually upgraded too.

So, what we should do now?
Thanks!

**Comment by donni106** [comment]
Thanks for clearance on (2) that there is no setting. And yes, we understand that we need modifying code for places like this.
What do you mean with theme? Is it possible to integrate in our extension, or is this something different? If we can integrate it here, please start with telling us, what files and folders need to be added where for this particular case. We can then decide if this would work for all other places as well or if we need to think in different way. And sure, official HumHub updates need special care, we are aware of that.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Theme is basically contains files and folder structure like default humhub theme(know as humhub) located in protected->humhub

![image](https://user-images.githubusercontent.com/103625795/176841754-6d5178d9-c6b3-4166-875c-48827a7ab12b.png)

**And how we can modify the existing code in humhub theme?** 
We can create our new humhub theme which is basically a copy of default humhub theme and in this new theme we can modify that code or file.

**How we can see our custom theme in web?**
By simple select theme in administration->setting->apperance and select theme from dropdown menu.

![image](https://user-images.githubusercontent.com/103625795/176842589-3f319bb0-fdd2-4a03-8eec-ee7fe17436ce.png)

And for more information about theme, you can check humhub official doc.
https://docs.humhub.org/docs/theme/structure/

**Comment by donni106** [comment]
So with an own theme we can manipulate existing views like forms, buttons and so on?
Can you create a new theme like you mentioned, based on HumHub default, and remove the two checkboxes from screenshot two?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Okay, we will make a custom theme!

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We have a question to ask
How we will push this custom theme we will build? because it is outside the smartVillageApp Module

**Comment by donni106** [comment]
Allright, I have created a new repository where you can work on the themes: https://github.com/ikuseiGmbH/smart-village-app-humhub-theme
There is a first issue to setup the theme: https://github.com/ikuseiGmbH/smart-village-app-humhub-theme/issues/1

**Comment by donni106** [comment]
After that you can hide the two checkboxes with this issue: https://github.com/ikuseiGmbH/smart-village-app-humhub-theme/issues/2
