### ISSUE TITLE
Support of recurring events

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#38]
Recurrence of events is already implemented for the calendar and can be used in the web application: https://github.com/humhub/calendar
There is a form where users can select several options:

|recurrence or not|daily|weekly|monthly|monthly end|yearly|
|---|---|---|---|---|---|
|![Bildschirmfoto 2022-06-27 um 15 37 45](https://user-images.githubusercontent.com/1942953/175955344-40c59aa8-1868-4a3a-a317-3ef99772403f.png)|![Bildschirmfoto 2022-06-27 um 15 38 01](https://user-images.githubusercontent.com/1942953/175955388-4c92ebfa-a1d0-418c-87a2-c36457062a58.png)|![Bildschirmfoto 2022-06-27 um 15 38 09](https://user-images.githubusercontent.com/1942953/175955414-8f975334-c779-4146-a5c9-4824dc0eff70.png)|![Bildschirmfoto 2022-06-27 um 15 38 25](https://user-images.githubusercontent.com/1942953/175955439-269bd0cd-dd56-4ecc-8d3d-ca2c0d643df5.png)|![Bildschirmfoto 2022-06-27 um 15 38 38](https://user-images.githubusercontent.com/1942953/175955457-8aa2ca68-8d64-466f-8e27-5670f8ffaf4b.png)|![Bildschirmfoto 2022-06-27 um 15 38 48](https://user-images.githubusercontent.com/1942953/175955478-313a6840-a47f-4a49-88f8-e873431df529.png)|

For the API it is missing in the default rest module. There was an issue opened in February 2021, which was never addressed: https://github.com/humhub/rest/issues/50

Can we extend the functionality with our extension and implement the missing pieces for creating recurring events?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Okay, we will create a new endpoint for creating calendar entry like /calendar/container/<containerId:\d+>.

ContainerId = it is user id that we will pass
Thanks!

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
I have a question to ask 
Do you need to show details of recurrence in API response? because recurrence information stored in very complicated way in database like this
![image](https://user-images.githubusercontent.com/103625795/177524745-d39a7373-2bd3-4f14-ad8d-e8d3d06c59ac.png)

So, it is difficult to convert this data into human readable format.

**Comment by donni106** [comment]
> Do you need to show details of recurrence in API response?

I don't think so. Do you have an example response that will be possible? So I can say if that is enough for our use cases.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Okay, so here is the response which we getting while creating calendar entry.

![image](https://user-images.githubusercontent.com/103625795/177545740-69ed5aa1-a95c-454c-bbd1-ff45cd24bd4a.png)

![image](https://user-images.githubusercontent.com/103625795/177545833-52bfc625-6c7d-44cb-b651-5ccf6787410c.png)

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We are waiting for you reply for this point
Thanks!

**Comment by donni106** [comment]
I did not have the time to check that yet, sorry.

**Comment by gaurav-handysolver** [comment]
No problem!

**Comment by donni106** [comment]
Can you please explain more in detail. I am not sure what happens when.
1. What will users be able to call with which parameters to create recurring events?
2. What will users be able to call to receive events that are recurring? How does responses look like?
3. Is an event that happens three times also three times in the results of requesting all events or is it included once with additional infos that makes it able to present three times?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Ans 1. We need the following parameter to create recurring event
1. frequency = it is represent what type of repeat event you will choose (never=>-1, year => 0, month => 1, week => 2,  day => 3).

2. interval = it is represent the difference between current and next event . it is accepted interger value .

3.  weekDays = it is represent week days, when you select week => 2 value in frequency (sunday => 1, monday => 2 and so on).

4.  monthDaySelection = it  is represent day of month that recurrence event happen like (Monthly on day 15 => 1, Monthly on the third Friday => 2). it is required when you select month in frequency .

5.  end = it is represent when you end this recurrence event (never => 0, onDate = > 1, After (occurrences )=> 2 )

6. endDate = it is represent end date when you end this recurrence event, it is required when you select (onDate => 1).

7.  endOccurrences = it is represent number of times this event will be happen like we want activate this event next 5 day so, we insert 5 in this parameter as value.

![image](https://user-images.githubusercontent.com/103625795/179174815-6d7b7f2b-f65e-45b0-bee7-5475ae693968.png)

Ans 2.  After creating the recurring event, the user will get response like (FREQ=DAILY;COUNT=5;INTERVAL=1).
frequency = daily, count(endOccurence) = 5 and interval = 1  

Ans 3.  When we create an event and that event we want recurring event then in that case we only mentioned how many times we want to repeat this event with the help of 'endOcurrence' parameter. we don't need additional information that makes it ables to present three times.

Thanks!

**Comment by donni106** [comment]
> Ans 1. We need the following parameter to create recurring event
> 
> ![image](https://user-images.githubusercontent.com/103625795/179174815-6d7b7f2b-f65e-45b0-bee7-5475ae693968.png)

is this the object that needs to be passend when creating an event?

> Ans 2. After creating the recurring event, the user will get response like (FREQ=DAILY;COUNT=5;INTERVAL=1). frequency = daily, count(endOccurence) = 5 and interval = 1
> Ans 3. When we create an event and that event we want recurring event then in that case we only mentioned how many times we want to repeat this event with the help of 'endOcurrence' parameter. we don't need additional information that makes it ables to present three times.

my question is, how are the events returned by the api? example: if i want to show events in a calendar and i have an event every tuesday of a month. i would like to mark every tuesday of a month for the user. so in a month with 4 tuesdays there should exist four events, right? when querying the endpoint for all events, will there be four events? or will there be one event? if there will be just one event, how do i know, that i need to mark 4 tuesdays in a month?
any questions on that or did you understand my problem?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Yes we understand your problem and we checked the api that fetching all calendar events (/calendar) and there is no information present related to recurring event so, when we fetching event which is recurring then it is not showing any recurrence information.

For example : id = 26

![image](https://user-images.githubusercontent.com/103625795/179455809-87e59503-eda2-4c69-a335-a83719547e00.png)

And we fetching the result it looks like

![image](https://user-images.githubusercontent.com/103625795/179455907-c2953e96-520b-49de-b792-aa748dc66bf0.png)

furthere more

![image](https://user-images.githubusercontent.com/103625795/179455968-4cfeceb7-235c-475b-88ea-5f4ec2a49916.png)


![image](https://user-images.githubusercontent.com/103625795/179458877-40f6e6d6-da1e-45b2-9c48-dbce372dc32f.png)

I Hope it will clear your problem
Thanks!

**Comment by donni106** [comment]
We knew, that there are no information about recurring events currently in the calendar API, that was why we created the issue for you :)

How would the result look like after your solution? What is the `RecurrenceFormModel`? Is this passed as param to the API on creation or a new part in the result when fetching calendar data?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 

The result is looking like this

![image](https://user-images.githubusercontent.com/103625795/179519402-04d425aa-154c-4be3-9a9b-b2ad92655885.png)

RecurrenceFormModel is the model which is responsible for saving recurring events.

![image](https://user-images.githubusercontent.com/103625795/179519902-a4c9750b-2469-421d-ab29-6eead82975da.png)

Sending Recurring data in payload

![image](https://user-images.githubusercontent.com/103625795/179520128-0489202b-4326-494b-a673-6e2feb79803b.png)

**Comment by donni106** [comment]
Ok I think we now have a common understanding about the complexity.
Please implement the solution that will return multiple events according to the recurrence form model.
Considering your screenshots, this would correspond to:
1. json returning calendar entries on every Wednesday 
and 
2. json returning three calendar entries on Wednesdays 13.07., 20.07. and 27.07. because of start and end date
right?

**Comment by Gk29-dev** [comment]
> Please implement the solution that will return multiple events according to the recurrence form model.

Okay, we will implement that



> 3. json returning three calendar entries on Wednesdays 13.07., 20.07. and 27.07. because of start and end date
> 
> right?

Yes

**Comment by gaurav-handysolver** [comment]
> Please implement the solution that will return multiple events according to the recurrence form model.

Okay, we will implement that



> 3. json returning three calendar entries on Wednesdays 13.07., 20.07. and 27.07. because of start and end date
> 
> right?

Yes

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Should we create a new endpoint showing a list of recurring events in a specific date range?
Example : /calendar/events

**Comment by donni106** [comment]
When we check calendar data, recurrence should be part of it. I guess it would be very hard to ask for recurrence separately. Requesting events in all available kinds should contain recurrence, if exists. When one asks for events, it is expected to receive all the events no matter if they are one time events or recurring events, right?

- `/calendar/entry/{id}`
- `/calendar/container/{id}`
- `/calendar`

Did I miss some endpoint?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Yes, we can use or implement recurring events details in the above endpoints you mentioned but for recurring events, we have to pass additional starting and ending dates (specific date range).

If we do not provide any dates then we have to think of other approaches as well for recurring events

What are your thoughts?

**Comment by donni106** [comment]
We will have calendar views, so requests could have monthly ranges. On the other hand we will have requests for events from today up to the future, so we can have a range from today to 31.12.2100 or something if we really need an end date.
I cannot think of any case were we are not able to set a range.

**Comment by gaurav-handysolver** [comment]
Okay @donni106 
So, we will modify the above endpoints (you mentioned) so, that recurrence events will be shown, if available right?

**Comment by donni106** [comment]
Yes please 🤝

**Comment by Gk29-dev** [comment]
Hi @donni106 
Can you tell us which data you want to see in recurring events?

![image](https://user-images.githubusercontent.com/56824739/182090596-ff316b6e-8ffd-437b-8ee9-cd73688a0ae8.png)
Thanks!

**Comment by donni106** [comment]
Is it ok to say: the same as for not recurring events? I guess every event should provide the same data? Or what exactly is the question?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
The last comment by mistake was sent through my personal GitHub account so, please don't mention that username for further conversation

**Comment by gaurav-handysolver** [comment]
> Is it ok to say: the same as for not recurring events? I guess every event should provide the same data? Or what exactly is the question?

Actually, recurring events return some additional data like backgroundColor, view mode, etc. So, we are asking what data should be returned from recurring events.

**Comment by donni106** [comment]
> Actually, recurring events return some additional data like backgroundColor, view mode, etc. So, we are asking what data should be returned from recurring events.

all right, so I would say that we do not need to exclude anything, let's return everything available?

**Comment by gaurav-handysolver** [comment]
Okay @donni106

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We are facing a problem while fetching the recurring events. when we are fetching events without bearer token, the recurring events not getting but when we add bearer token/BaseContentController class then it is running fine.

So, if we add BaseContentController class in our CalendarController then issue #6 will be invalid, and if we will not add that class then recurring events not fetching.

We still can't find why this is happening

What we should do now? Will we create new endpoints

**Comment by donni106** [comment]
What about having a new controller and a new endpoint especially for recurring calendar events and keep the current calendar events untouched? this way it should be still possible to fetch calendar events without bearer token, right?
and if we want to show all calendar events we need to fetch the regular calendar events and the recurring calendar events in addition. this would result in always fetching two endpoints for calendar events, with or without bearer token.
could this be a solution?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Yes, this will be the solution. we will create a new controller and new endpoint for the recurring events so, if you want to fetch recurring events then pass the bearer token and you will get all the recurring events in that date range

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
One question: what will be the name of the new recurring endpoint?

**Comment by donni106** [comment]
All right, let's do:

`GET /calendar/recurring`
`GET /calendar/container/{containerId}/recurring`

Will there be an endpoint to get one recurring event like `GET /calendar/entry/{id}`? Do these recurring events have IDs?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We have a doubt: do you want only recurring events will be shown in these endpoints?
For example :
There are three events, 2 events are recurring and one is not so, the non-recurring event will be shown or not in that date range?

**Comment by donni106** [comment]
If the non recurring event would be returned by `/calendar` it should not be returned with `/calendar/recurring`. Does this answer the question?

**Comment by gaurav-handysolver** [comment]
Yes @donni106 
Thanks!
