### ISSUE TITLE
Join spaces with join policy 2 (open)

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#39]
We found out, that spaces with an open join policy for registered users cannot be joined after changing user roles. We had to restrict space and user administration for everyone, so it is only possible for admins and space owners to use `POST /space/{spaceId}/membership/{userId}` for adding members. If a user tries to call that an error is returned: 

```json
{
  "code": 400,
  "message": "You cannot administer this space!"
}
```

I could not find out a different way to join a space per API. Is there any or can you create one please?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We can make the endpoint for this. It is not much difficult for us. But we are don't understand more clearly at what situation/scenario you are getting this error message.

Can you please explain this more in detail like how you restricted space and user admin for everyone? 
And which user role you are talking? if possible attached screenshot it will be very helpful for us
Thanks!

**Comment by donni106** [comment]
We need to allow all users in a group to manage spaces in order to join them through API:

![Bildschirmfoto 2022-07-12 um 12 09 27](https://user-images.githubusercontent.com/1942953/178466765-4fe696c5-1997-4bd8-9e8c-d0bba0407984.png)

If we set it to "Default - Deny" the error messages I posted before is returned for a user in that particular group when trying to join a public space.

Does this help?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Thanks for explanation!
