### ISSUE TITLE
Add read/unread status of conversations

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#4]
The `/mail` endpoint does not provide information about the read/unread status of conversations. We need a new key in the results of each conversation that marks the status.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Do we require auth bearer token for adding read/unread status of conversation?

**Comment by donni106** [comment]
yes, everything should be exactly as `mail` but with added read/unread status.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We implemented read/unread status of conversation but we have a doubt. Do you want to show the time(last_view) when user open the conversation for reading, if the status is read?

**Comment by donni106** [comment]
Good question. Having the time would be the best solution. We could have a `seen_at`, which is NULL by default and set to the time if read. So `unread = seen_at NULL` and `read = seen_at 2022-05-04 13:16:34`?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Actually, we implemented a logic in which this seen_at is only visible when conversation is read, otherwise it will not include in result.

**Comment by donni106** [comment]
Can you show the current result which is in development? So there will be a `read` + `seen_at`?

**Comment by donni106** [comment]
Nice, but i think the `seen_at` should be returned anyways (with `null` for `unread`). So we ensure having always the same keys in the results with different values.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Currently we are checking only starting message on any converstion is read/unread and based on this we set status is read/unread. Do you want to every message of conversation will be check whether it is read or unread?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
As of now, it is depend on starting(first message) not on the latest one

**Comment by donni106** [comment]
Regarding GitHub here, the starting message was:

> The `/mail` endpoint does not provide information about the read/unread status of conversations. We need a new key in the results of each conversation that marks the status.

This should be the reference now for the whole conversation?

Wouldn't your message from 5 hours ago be the point for checking, if i have unread messages.
I think messages from the past are already read. Only new ones are not read at some time.
So for you now, this message i write currently is the only one that is not read yet, right?

Can you explain please, how it would work with depending on the starting message?
