### ISSUE TITLE
Uniform routes for link list delete endpoints

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#41]
In the following two examples the endpoint route is `delete/...`:

https://github.com/ikuseiGmbH/smart-village-app-humhub-ext/blob/4b7ebb0d8859b0e95f19acae65c08cd2c9bc2da9/Events.php#L78

https://github.com/ikuseiGmbH/smart-village-app-humhub-ext/blob/4b7ebb0d8859b0e95f19acae65c08cd2c9bc2da9/Events.php#L85

Is there any specific reason for this decision or can we have `/category/<categoryId:\d+>` and `/link/<linkId:\d+>` with `'verb' => 'DELETE'` that identifies clearly the action? I guess that would follow best practices more.

**Comment by gaurav-handysolver** [comment]
> Is there any specific reason for this decision or can we have `/category/<categoryId:\d+>` and `/link/<linkId:\d+>` with `'verb' => 'DELETE'` that identifies clearly the action? I guess that would follow best practices more.

Hi @donni106 
No, specific reason to add this 'delete' word in URL, Yes we can change the URL in newly created branch (issue-41)

**Comment by donni106** [comment]
All right thanks, please do so for consistency.
