### ISSUE TITLE
Rewordings does not apply online

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#44]
Hi @gaurav-handysolver, we added some overrides for messages as explained in #34 with the PR: #43.
I have tried to put this on staging but without success. The new texts are not applied. I have tried different things and ended up with the following folder structure:

![Bildschirmfoto 2022-07-29 um 17 28 37](https://user-images.githubusercontent.com/1942953/181793590-2252b02f-164f-4c32-a3a5-ac3c69fc27c9.png)

Any idea what could be wrong?
Thanks.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Did you change the language from the admin section as well? (see the attached screenshot below)

![image](https://user-images.githubusercontent.com/103625795/182116093-86050819-be40-45eb-a897-38cd4e9185e9.png)

**Comment by donni106** [comment]
Yes, it was and is German.

**Comment by donni106** [comment]
It works now! Our team fixed a docker issue, which was blocking the `de` folder to be deployed.
