### ISSUE TITLE
Every registered user should be able to access membership lists in order to find out if member or not

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#45]
I just found out, that I cannot access membership lists for space, even with an user that is member of a particular space.
There is some security check so that only admins can access?

<img width="980" alt="Bildschirmfoto 2022-08-03 um 16 55 25" src="https://user-images.githubusercontent.com/1942953/182642650-0d65798e-297b-40ec-b09c-17f7e423e12d.png">

We nee every registered user to list memberships in order to find out if the user is a member of a space or not.
Please update `/space/{id}/membership` to return the data for every registered user and not only for admins.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Is this endpoint we created? This error is showing because the group_id of the user (you passed in the bearer token is not the admin of the space or site admin) i.e group_id = "member".

**Comment by donni106** [comment]
No, the endpoint is a default one from Humhub.
The bearer token passed is the one of a user, no matter if already member of a space or not. This should be possible without admin role, because otherwise we cannot find out technically if a user is a member of a space.

**Comment by gaurav-handysolver** [comment]
Okay @donni106,
We can make a new endpoint /space/<space:id>/membership where you will get all the members of that space. One question will we pass the bearer token for this endpoint?

**Comment by donni106** [comment]
So we will have a v2 of the endpoint without restriction?
Yes please pass bearer token, as only registered users should be allowed to fetch.

**Comment by gaurav-handysolver** [comment]
Okay @donni106 
We will make an endpoint where you will get all the members of that space
