### ISSUE TITLE
Allow access of user by id by registered users

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#48]
The endpoint `GET /user/{id}` returns a **403 Forbidden** if "normal" registered users calls it. It should be possible to fetch data for users per id by all registered users and not only admins. Please remove the restriction, that only admins can receive specific user data.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Can we create a new endpoint /api/v2/user/<userId> for this issue? because it will be easy for us to resolve this issue

**Comment by donni106** [comment]
You mean with id, right? `GET /api/v2/user/{id}`, yes.

**Comment by gaurav-handysolver** [comment]
Yes

**Comment by donni106** [comment]
i did not receive a notification for your edited post and just saw it now.
yes please, only with bearer token.

**Comment by gaurav-handysolver** [comment]
Okay, in that case
We will make a new controller because in our user controller we are not passing bearer tokens for requests.

**Comment by donni106** [comment]
Can you work on this next please?
