### ISSUE TITLE
Add date range filter for calendar query

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#57]
Can you please add a filter for `start_date` and `end_date` for the `GET /calendar` and `GET /calendar/container/{id}` in v2 like already implemented with recurring events endpoint? This will allow us to filter calendar entries for specific days.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
These two parameters will be compulsory to add in URL  for getting calendar entries?

**Comment by donni106** [comment]
No, like other params as limit or page they are not necessary but optional ones. They can exist to filter the list, or not to receive all.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
There will be two scenarios that I want to discuss.

1. If the user not pass start_date but he is passing the end_date. (In this scenario we can take the current date as start_date ?)
2. If the user passes start_date but not pass the end_date

**Comment by donni106** [comment]
1. can we filter for "event_date <= end_date" in that case?
2. can we filter for "event_date >= start_date" in that case?

and if both are given we are inside with "start_date <= event_date >= end_date"?
