### ISSUE TITLE
Allow to read public contents without login through API

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#6]
Currently everything in HumHub is only accessible after registration and login. After login there are restrictions for contents like "public" and "private", which both applies for logged in users. Is it possible to update the access rights for some contents so that they can be read by people without an account?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Yes, it is possible to update the access rights for some content so, they can be read by people without login.

You have to change the following setting.

For example, to access the post without login
1. Create any post in the space 
   (In our example we create two post in daily news space)
  
![image](https://user-images.githubusercontent.com/103625795/167564186-190bc061-9419-4f5d-a8af-08cfe7ab92b2.png)

2. After creation, go to the space security
   
![image](https://user-images.githubusercontent.com/103625795/167564678-a071172d-8d8b-44bf-9db2-007b4431a29f.png)

 3. In general tab of space security, select the visibility option from public to visible to all.
 
![image](https://user-images.githubusercontent.com/103625795/167565031-0fdebdcf-2e10-40a9-a472-666aea39f4d5.png)

* Now you can open the space url and see how many posts are in that space
![image](https://user-images.githubusercontent.com/103625795/167565340-8c5a3570-c3b9-4345-803d-f56072bda80c.png)


**You can also show the content of a particular post without login**

1.  Just click on the change to "public" option and now you can see your post content.
![image](https://user-images.githubusercontent.com/103625795/167565664-a7ecd621-bab3-4259-a413-0816ff8d8c32.png)

See the below image.
![image](https://user-images.githubusercontent.com/103625795/167565776-f2527b62-63b3-418f-bcdd-44c8999b65a6.png)


Thanks!

**Comment by donni106** [comment]
Thanks so far. I haven't seen that option in the dropdown. First i needed to allow guest access at all for the instance. Now i have that option. I have successfully tested public/private on the web

I have updated the issue to "API" because it had no effect there. When calling endpoint without bearer token, we get:

```
{
	"name": "Unauthorized",
	"message": "Invalid token!",
	"code": 0,
	"status": "401",
	"type": "yii\\web\\HttpException"
}
```

What do you think is needed to allow "guest" access for public data per API?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Can you share the endpoint url where you tested it?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Can you share the endpoint url where you tested it?

**Comment by donni106** [comment]
`/post`, `/space` and `/calendar`

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Yes, we can bypass the authentication and for that we can create own functions, which will be pretty much similiar to the core functions but these new functions will not authenticate the user.

Also can you share which contents should be publicly read like you already mentioned /post, /space and /calender any other? 

Thanks!

**Comment by donni106** [comment]
Sounds good!
The new endpoints without authentication must be readonly and only return data, that is configured as "public + guests", which should be always `visibility: 2` i guess.

Lets start with:
- `/space`
- `/space/{id}`
- `/calendar`
- `/calendar/container/{container-id}`
- `/calendar/entry/{id}`
- `/post`
- `/post/container/{container-id}`
- `/post/{id}`

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We have a doubt, /calendar/container/{container-id} and /post/container/{container-id} endpoints is using to create post and calendar for specific container. They both are not readonly endpoint and they might be run after the authentication.
So, are you sure you want to create these endpoints without login?

Thanks!

**Comment by donni106** [comment]
No, all endpoints should be `GET` requests and readonly. Nothing should be used to create something.
Example for `/calendar/container/{container-id}`:

<img width="1227" alt="Bildschirmfoto 2022-05-16 um 11 32 02" src="https://user-images.githubusercontent.com/1942953/168563134-c5062963-ae7f-4de1-a6c1-74f26ab9171e.png">
