### ISSUE TITLE
Provide endpoints for the link list module

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#7]
Currently there is nothing present for the link list module in the rest module. With having the link list installed in an HumHub instance we need to be able to access its data also per API.

Spaces can have link lists like files. For files there are several endpoints existing, which we can use as a base for the link lists:

<img width="201" alt="Bildschirmfoto 2022-04-13 um 16 25 57" src="https://user-images.githubusercontent.com/1942953/163202850-383fae91-ae68-406f-8113-cdafe0145d03.png">

We need to get links for a specific container and by id as well as functionalities to create and delete links.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We investigated the link list module for space and we have following queries.

1. While creating the links for space first, we have to create category and then name of the url so, for this we have two options

-  First one is, make two separete endpoints first one for to create category and second one is name of the url
- And second one is, pass category name in the endpoint url, and check if category name is  present or not, if not, then it will create the that category.  

2. How we can pass url value?
  Through query like /space/link/mountains/visit?val="https://www.google.com"
    * mountains : name of the category.
    * visit: name of the url
    * val = value of the url pass in val    

If you have any suggestion then feel free to share with us.
Thanks!

**Comment by donni106** [comment]
Allright, let me think about that. I do not understand you proposal for 2.. It sounds too complicated for me and does not reflect all actions i guess.

We need endpoints for link categories first. So we should implement all restful endpoints for categories first (`get` all categories, `get` one category, `post` create new category, `put` edit one category, `delete` one category). For `post` and `put` there should be JSONs to pass data. The data should be the same as in the web:

![Bildschirmfoto 2022-05-10 um 11 47 28](https://user-images.githubusercontent.com/1942953/167600698-a8e1d7f1-fa49-44ae-927f-1f1df1b90473.png)

- title
- description
- sorter

Next we need are endpoints for links. We should implement all restful endpoints here as well (`get` all links, `get` one link, `post` create new link, `put` edit one link, `delete` one link). For `post` and `put` there should be JSONs to pass data. The data should be the same as in the web with an additional `categoryId` from the belonging category:

![Bildschirmfoto 2022-05-10 um 11 42 33](https://user-images.githubusercontent.com/1942953/167601006-acdaa871-ec25-42d7-9466-2937e2117b99.png)

- title
- description
- url
- sorter
- categoryId

We also should add an endpoint for getting all links in a certain category.

Any questions or opinions?
Please plan and share the endpoints before you implement them.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Thanks for explaining each and evey thing in detail. We will share endpoints very soon!

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We suggesting you some endpoints for categories as well as links.

**For categories.**
   /categories - (get all categories) - method(GET)
  /category/{category-id}  - (get one category by it's id) - method(GET)
  /category - (create new category)  - method(POST)
  /category/{category-id} - (edit category by it's id) - method(PUT)
 /category/delete/{category-id} - (delete category by it's id) - method(DELETE)

/category/{category-id}/links - (get all links in the id) - method(GET)

**For links**
  /links - (get all links) - method(GET)
 /link/{link-id} - (get one link by it's id) - method(GET)
 /link - (create new link) - method(POST)
 /link/{link-id} - (edit link by it's id) - method(PUT)
 /link/delete/{link-id} - (delete link by it's id) - method(DELETE)

Feel free to share your thoughts on this
Thanks!

**Comment by donni106** [comment]
> /category/delete/{category-id} - (delete category by it's id) - method(DELETE)
> 
> /link/delete/{link-id} - (delete link by it's id) - method(DELETE)

we do not need the `/delete` in this here. it should be `DELETE /category/{category-id}` and `DELETE /link/{link-id}` please.

> /category/{category-id}/links - (get all links in the id) - method(GET)

i suggest to move the links for a category to the links "section" because the result are links and not categories: `GET /link/category/{category-id}`

this also fits more to the existing endpoints where something is "filtered" by containers, for example `GET /calendar/container/{container-id}`

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We have a doubt.
All the links are belongs to any category so, we have to pass category id as well for the following endpoints:
/link/{link-id} - (get one link by it's id) - method(GET)
/link - (create new link) - method(POST)
/link/{link-id} - (edit link by it's id) - method(PUT)
/link/delete/{link-id} - (delete link by it's id) - method(DELETE)

The new endpoints should be look like this.
/link/{categoryId}/{link-id} - (get one link by it's id) - method(GET)
/link/{categoryId} - (create new link) - method(POST)
/link//{categoryId}/{link-id} - (edit link by it's id) - method(PUT)
delete/link/{categoryId}/{link-id} - (delete link by it's id) - method(DELETE)

What's your suggestion?

**Comment by donni106** [comment]
isn't it only necessary to pass a `categoryId` for `/link - (create new link) - method(POST)`? all the others have a specific link id, right? or can there be same link ids in different categories?
in the web i cannot create links with identical ids across different categories:

![Bildschirmfoto 2022-05-25 um 15 00 33](https://user-images.githubusercontent.com/1942953/170268132-0a2c2934-b47b-41ef-b0c0-e1a0359b8f17.png)

and the url could stay `/link` when passing the `categoryId` as param?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
In the web, they are using guid of space and user to create links. 
We are also using guid of space and user. but for example we want to create a link in category 2 then how we will defined category for that newly link?.

>and the url could stay /link when passing the categoryId as mandatory param?
Yes we can pass the categoryId as param and the url will be stay as /link

see the example below
![image](https://user-images.githubusercontent.com/103625795/170282223-293388ce-7cbc-4d08-82d8-9dcaba7a31da.png)

**Comment by donni106** [comment]
yes, this seems like the way i was thinking. by passing the categoryId 2 for example, a link should be created in category 2.
do i understand correctly, that the guid of a category is also necessary?

**Comment by gaurav-handysolver** [comment]
Hi @donni106
That was space's guid not category guid. we mainly can created links and category in space and user so, we have to pass this guid of space or user in categories as well as links endpoints.
