### ISSUE TITLE
Add endpoint to list "all my spaces"

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#8]
Currently it is possible to list all spaces with `/space` that "I" created but we also need to list alle spaces that "I am" a member of in addition. I would suggest a new GET endpoint `/space/my` based on `/space` that includes spaces where the current user is owner as well as member.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We checked  /space endpoint and we found that the /space endpoint is also provide list of all spaces where the user is owner as well as member so, can you check it again?

Or we missing something else?

**Comment by donni106** [comment]
Thanks, my new test show two different spaces when calling `/space`. For one space i am the owner and the other space has a different owner, so I am "just" a member. This should be enough for our cases. If anything else comes up, I will create a new issue.

**Comment by donni106** [comment]
@gaurav-handysolver I need to come back to this. As a user I want to have all my spaces listed. 
Currently `/space` lists all spaces that exist and I can not figure out how to filter to the ones a user is a member of. There is an info missing, if the requesting user is a member or not. How can we achieve this? Do we need a new endpoint or can you update the `/space` endpoint with an info about the membership?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Do you need the list of spaces where a user is the only member in those spaces?

**Comment by donni106** [comment]
I think we mean the same but I will repeat in a different way.
When fetching `/space` we receive all spaces available. There is no information if the user, that is requesting all spaces, is a member of some of those spaces or not. With adding such information we could filter all spaces of a user where the user is a member. Or we need an additional endpoint receiving only those spaces a user is a member of.

**Comment by donni106** [comment]
@gaurav-handysolver any answer to this? Can there be an info not only about the owner of a space but also if the requesting user is a member? Something like `member_status: 0 | 1 | 2 | 3` corresponding to the status that is returned by `GET /space/{id}/membership`.

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We think that for the list of spaces where the user is a member in those spaces, we can achieve this task by creating a new endpoint like /space/membership/<userId>. 
It will return all the spaces in which the user will be a member. we can also provide some additional information like what is the role of the user in that space (i.e admin, member, etc.)

**Comment by donni106** [comment]
Good idea! `/space/membership` seams too similar to the existing membership actions, please create `GET /space/user`, which identifies the user by bearer token.
It should have all the data returned like `GET /space` with additionally the `member_status` and the `user_role`.

**Comment by gaurav-handysolver** [comment]
Okay @donni106

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We are adding a function in the membership controller because in that controller we are taking the bearer token for each request call.

**Comment by donni106** [comment]
ok, does `GET /space/memberships` fit better in this case? i think so.

**Comment by gaurav-handysolver** [comment]
Okay @donni106 
We will change the endpoint URL to /space/memberships
